#!/usr/bin/env bash

/usr/local/spark-2.2.0/bin/spark-submit  --class bd.edu.e_zcxc --executor-memory 8g --driver-memory 4g /home/bigdata/cq2tasks/dataana4cq2.jar; /usr/local/spark-2.2.0/bin/spark-submit  --class bd.edu.e_bsgs --executor-memory 8g --driver-memory 4g /home/bigdata/cq2tasks/dataana4cq2.jar

